# CMake generated Testfile for 
# Source directory: /workspace/cmake-3.28.3/Tests/CMakeLib
# Build directory: /workspace/cmake-3.28.3/Tests/CMakeLib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[CMakeLib.testArgumentParser]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testArgumentParser")
set_tests_properties([=[CMakeLib.testArgumentParser]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestBinPacker]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testCTestBinPacker")
set_tests_properties([=[CMakeLib.testCTestBinPacker]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceAllocator]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testCTestResourceAllocator")
set_tests_properties([=[CMakeLib.testCTestResourceAllocator]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceSpec]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testCTestResourceSpec" "/workspace/cmake-3.28.3/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testCTestResourceSpec]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceGroups]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testCTestResourceGroups")
set_tests_properties([=[CMakeLib.testCTestResourceGroups]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebug]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testDebug")
set_tests_properties([=[CMakeLib.testDebug]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testGccDepfileReader]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testGccDepfileReader" "/workspace/cmake-3.28.3/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testGccDepfileReader]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testGeneratedFileStream]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testGeneratedFileStream")
set_tests_properties([=[CMakeLib.testGeneratedFileStream]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testJSONHelpers]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testJSONHelpers")
set_tests_properties([=[CMakeLib.testJSONHelpers]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testRST]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testRST" "/workspace/cmake-3.28.3/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testRST]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testRange]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testRange")
set_tests_properties([=[CMakeLib.testRange]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testOptional]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testOptional")
set_tests_properties([=[CMakeLib.testOptional]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testString]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testString")
set_tests_properties([=[CMakeLib.testString]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testStringAlgorithms]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testStringAlgorithms")
set_tests_properties([=[CMakeLib.testStringAlgorithms]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testSystemTools]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testSystemTools")
set_tests_properties([=[CMakeLib.testSystemTools]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUTF8]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testUTF8")
set_tests_properties([=[CMakeLib.testUTF8]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testXMLParser]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testXMLParser")
set_tests_properties([=[CMakeLib.testXMLParser]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testXMLSafe]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testXMLSafe")
set_tests_properties([=[CMakeLib.testXMLSafe]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testFindPackageCommand]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testFindPackageCommand")
set_tests_properties([=[CMakeLib.testFindPackageCommand]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVProcessChain]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testUVProcessChain" "/workspace/cmake-3.28.3/Tests/CMakeLib/testUVProcessChainHelper")
set_tests_properties([=[CMakeLib.testUVProcessChain]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVRAII]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testUVRAII")
set_tests_properties([=[CMakeLib.testUVRAII]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVStreambuf]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testUVStreambuf" "/workspace/cmake-3.28.3/bin/cmake")
set_tests_properties([=[CMakeLib.testUVStreambuf]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtMemory]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testCMExtMemory")
set_tests_properties([=[CMakeLib.testCMExtMemory]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtAlgorithm]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testCMExtAlgorithm")
set_tests_properties([=[CMakeLib.testCMExtAlgorithm]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtEnumSet]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testCMExtEnumSet")
set_tests_properties([=[CMakeLib.testCMExtEnumSet]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testList]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testList")
set_tests_properties([=[CMakeLib.testList]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMakePath]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testCMakePath")
set_tests_properties([=[CMakeLib.testCMakePath]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerAdapter]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testDebuggerAdapter")
set_tests_properties([=[CMakeLib.testDebuggerAdapter]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerAdapterPipe]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testDebuggerAdapterPipe")
set_tests_properties([=[CMakeLib.testDebuggerAdapterPipe]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerBreakpointManager]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testDebuggerBreakpointManager")
set_tests_properties([=[CMakeLib.testDebuggerBreakpointManager]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerVariables]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testDebuggerVariables")
set_tests_properties([=[CMakeLib.testDebuggerVariables]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerVariablesHelper]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testDebuggerVariablesHelper")
set_tests_properties([=[CMakeLib.testDebuggerVariablesHelper]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerVariablesManager]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLibTests" "testDebuggerVariablesManager")
set_tests_properties([=[CMakeLib.testDebuggerVariablesManager]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;89;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerNamedPipe-Project]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/testDebuggerNamedPipe" "/workspace/cmake-3.28.3/bin/cmake" "/workspace/cmake-3.28.3/Tests/CMakeLib/DebuggerSample" "/workspace/cmake-3.28.3/Tests/CMakeLib/DebuggerSample")
set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Project]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;112;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testDebuggerNamedPipe-Script]=] "/workspace/cmake-3.28.3/Tests/CMakeLib/testDebuggerNamedPipe" "/workspace/cmake-3.28.3/bin/cmake" "/workspace/cmake-3.28.3/Tests/CMakeLib/DebuggerSample/script.cmake")
set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Script]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;112;add_test;/workspace/cmake-3.28.3/Tests/CMakeLib/CMakeLists.txt;0;")
subdirs("PseudoMemcheck")
